// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldhltpmdsoxbrtmbzgea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkaGx0cG1kc294YnJ0bWJ6Z2VhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3NjkzNDUsImV4cCI6MjA1MDM0NTM0NX0.M2DGwwQMgT37PRqSo-JyysqdDg09mZ5W_UsGHr4DywM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);